wandb_version: 1

epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 200
lr:
  desc: null
  value: 1.0e-06
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686020180.047714
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.3
      8:
      - 3
      - 5
